# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Phil Fishbein
email: phil@fishbe.in
# subtitle: Your awesome subtitle
description: >- # this means to ignore newlines until "baseurl:"
  I'm Phil! I'm passionate about building cool stuff. When I'm not in front of a computer I'm probably behind a camera or on a bike.
author: Philip Fishbein
avatar: assets/img/me.png

# You'll want to customize url and baseurl for your own site:
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://fishbein.github.io" # the base hostname & protocol for your site

# Social settings
facebook_url: "https://facebook.com/philfishbein"
github_url: "https://github.com/fishbein"
googleplus_url:
instagram_url: "https://instagram.com/philfishbein"
linkedin_url: "https://linkedin.com/in/philfishbein"
pinterest_url:
slack_url:
twitter_url: "https://twitter.com/fishbein"

sass:
    sass_dir: ./_scss

# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
